export const CREATE_FLASH_MESSAGE = "CREATE_FLASH_MESSAGE";
export const CLOSE_FLASH_MESSAGE = "CLOSE_FLASH_MESSAGE";

export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";
export const AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR";

export const SET_CHAT_ROOM = "SET_CHAT_ROOM";
export const SET_SELECTED_USER = "SET_SELECTED_USER";
export const SET_MESSAGES = "SET_MESSAGES";