export const CREATE_FLASH_MESSAGE = "CREATE_FLASH_MESSAGE";
export const CLOSE_FLASH_MESSAGE = "CLOSE_FLASH_MESSAGE";

export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";
export const AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR";

export const SET_CHAT_LIST = "SET_CHAT_LIST";
export const SET_SELECTED_ROOM = "SET_SELECTED_ROOM";