export const CREATE_FLASH_MESSAGE = "CREATE_FLASH_MESSAGE";
export const CLOSE_FLASH_MESSAGE = "CLOSE_FLASH_MESSAGE";

export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";
export const AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR";